//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LxShop.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long Customer_id { get; set; }
        public string Customer_name { get; set; }
        public Nullable<long> phone { get; set; }
        public string email { get; set; }
        public string Password { get; set; }
        public string DistrictId { get; set; }
        public string ProvinceId { get; set; }
        public string Address { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
