//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LxShop.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_details
    {
        public long stt { get; set; }
        public long Order_id { get; set; }
        public long Product_id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> price_ship { get; set; }
    }
}
