//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LxShop.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Specifications
    {
        public long Stt { get; set; }
        public string Specification_Id { get; set; }
        public string Specification_Name { get; set; }
        public string Screen { get; set; }
        public string Camera_rear { get; set; }
        public string Camera_Selfie { get; set; }
        public string RAM { get; set; }
        public string Internal_memory { get; set; }
        public string CPU { get; set; }
        public string GPU { get; set; }
        public string Battery_capacity { get; set; }
        public string SIM { get; set; }
        public string Operating_System { get; set; }
        public string Made_In { get; set; }
        public Nullable<System.DateTime> Launch_Time { get; set; }
        public string Product_Id { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
