//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LxShop.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long Stt { get; set; }
        public string Product_Id { get; set; }
        public string Product_Name { get; set; }
        public string ImgaeAvatar { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Original_Price { get; set; }
        public string Product_Category_TypeId { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public string Brand_id { get; set; }
        public Nullable<int> Is_Hot { get; set; }
        public string Description { get; set; }
        public string Product_Infor { get; set; }
        public Nullable<int> Old_New { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
